version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: festa_db
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: